
package cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EchoCPFService", targetNamespace = "http://controle/", wsdlLocation = "http://localhost:8081/EchoCPF?wsdl")
public class EchoCPFService
    extends Service
{

    private final static URL ECHOCPFSERVICE_WSDL_LOCATION;
    private final static WebServiceException ECHOCPFSERVICE_EXCEPTION;
    private final static QName ECHOCPFSERVICE_QNAME = new QName("http://controle/", "EchoCPFService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/EchoCPF?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECHOCPFSERVICE_WSDL_LOCATION = url;
        ECHOCPFSERVICE_EXCEPTION = e;
    }

    public EchoCPFService() {
        super(__getWsdlLocation(), ECHOCPFSERVICE_QNAME);
    }

    public EchoCPFService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECHOCPFSERVICE_QNAME, features);
    }

    public EchoCPFService(URL wsdlLocation) {
        super(wsdlLocation, ECHOCPFSERVICE_QNAME);
    }

    public EchoCPFService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECHOCPFSERVICE_QNAME, features);
    }

    public EchoCPFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoCPFService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EchoCPF
     */
    @WebEndpoint(name = "EchoCPFPort")
    public EchoCPF getEchoCPFPort() {
        return super.getPort(new QName("http://controle/", "EchoCPFPort"), EchoCPF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EchoCPF
     */
    @WebEndpoint(name = "EchoCPFPort")
    public EchoCPF getEchoCPFPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controle/", "EchoCPFPort"), EchoCPF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECHOCPFSERVICE_EXCEPTION!= null) {
            throw ECHOCPFSERVICE_EXCEPTION;
        }
        return ECHOCPFSERVICE_WSDL_LOCATION;
    }

}
